//go:build ignore

// Command generate writes text.go from the §10.2 table in the contract.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strings"
)

var row = regexp.MustCompile("^\\| `([^`]+)` \\| ([^|]+?) \\|")

func main() {
	raw, err := os.ReadFile("docs/contracts/orbit-contract-v2.md")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	text := string(raw)
	start := strings.Index(text, "### 10.2")
	end := strings.Index(text, "### 10.3")
	if start < 0 || end < start {
		fmt.Fprintln(os.Stderr, "section 10.2 not found")
		os.Exit(1)
	}
	var codes, messages []string
	for _, line := range strings.Split(text[start:end], "\n") {
		if strings.Contains(line, "触发条件") {
			break
		}
		m := row.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		codes = append(codes, m[1])
		messages = append(messages, strings.TrimSpace(m[2]))
	}
	if len(codes) != 7 {
		fmt.Fprintf(os.Stderr, "want 7 sentences, got %d\n", len(codes))
		os.Exit(1)
	}
	names := []string{"Timeout", "RateLimited", "ProviderError", "Auth", "Config", "StateUnreadable", "DecidedApprovalsLimit"}
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by go run internal/failtext/generate.go; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Sentences are the §10.2 table in docs/contracts/orbit-contract-v2.md.\n\npackage failtext\n\nconst (\n")
	for i, name := range names {
		fmt.Fprintf(&b, "\t%s = %q\n", name, messages[i])
	}
	fmt.Fprintf(&b, ")\n\nfunc Message(code string) (string, bool) {\n\tswitch code {\n")
	for i, code := range codes {
		fmt.Fprintf(&b, "\tcase %q:\n\t\treturn %s, true\n", code, names[i])
	}
	fmt.Fprintf(&b, "\tdefault:\n\t\treturn \"\", false\n\t}\n}\n")
	out, err := format.Source(b.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile("internal/failtext/text.go", out, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
