// Code generated by go run internal/failtext/generate.go; DO NOT EDIT.
// Sentences are the §10.2 table in docs/contracts/orbit-contract-v2.md.

package failtext

const (
	Timeout               = "模型响应超时，这一轮没跑完。"
	RateLimited           = "模型当前请求太多，请稍后再试。"
	ProviderError         = "模型服务暂时出错，这一轮没跑完。"
	Auth                  = "模型配置有问题，请联系管理员。"
	Config                = "模型配置有问题，请联系管理员。"
	StateUnreadable       = "此任务的运行状态已失效，无法继续。你可以查看记录，或新建任务继续工作。"
	DecidedApprovalsLimit = "此任务的审批次数已达上限，无法继续。你可以查看记录，或新建任务继续工作。"
)

func Message(code string) (string, bool) {
	switch code {
	case "timeout":
		return Timeout, true
	case "rate_limited":
		return RateLimited, true
	case "provider_error":
		return ProviderError, true
	case "auth":
		return Auth, true
	case "config":
		return Config, true
	case "state_unreadable":
		return StateUnreadable, true
	case "DECIDED_APPROVALS_LIMIT":
		return DecidedApprovalsLimit, true
	default:
		return "", false
	}
}
