// Command contractgen writes Go types for the Orbit v3 contract bundle.
//
// The bundle is orbit-runtime's schema/v3/contracts.json (exported from
// orbit_contracts.v3). It supports the JSON Schema subset pydantic produces
// for those models and fails on anything else, so a new construct cannot be
// silently mistyped:
//
//   - every $defs entry except JsonValue becomes a struct;
//   - x-unions entries (discriminated oneOf with x-go-type) become a struct
//     with one pointer per member plus MarshalJSON/UnmarshalJSON;
//   - x-enums entries become named string types with constants;
//   - optional scalars and structs are pointers, optional slices and maps use
//     omitempty, and const fields are plain strings.
//
// Usage: go run ./internal/contract/contractgen -in contracts.json -out contracts_gen.go -pkg contractv3
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

func main() {
	in := flag.String("in", "contracts.json", "contract bundle")
	out := flag.String("out", "contracts_gen.go", "Go file to write")
	pkg := flag.String("pkg", "contractv3", "Go package name")
	flag.Parse()

	data, err := os.ReadFile(*in)
	if err != nil {
		fail(err)
	}
	src, err := generate(data, *pkg)
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "contractgen:", err)
	os.Exit(1)
}

type schema = map[string]any

type bundle struct {
	Defs   map[string]schema   `json:"$defs"`
	Models []string            `json:"x-models"`
	Unions map[string]schema   `json:"x-unions"`
	Enums  map[string][]string `json:"x-enums"`
}

type generator struct {
	b         bundle
	out       bytes.Buffer
	unions    map[string]schema // by x-go-type
	enumByKey map[string]string // sorted values -> enum name
	usesTime  bool
}

func generate(data []byte, pkg string) ([]byte, error) {
	var b bundle
	if err := json.Unmarshal(data, &b); err != nil {
		return nil, fmt.Errorf("read bundle: %w", err)
	}
	g := &generator{b: b, unions: map[string]schema{}, enumByKey: map[string]string{}}
	for name, values := range b.Enums {
		g.enumByKey[enumKey(values)] = name
	}
	for _, u := range b.Unions {
		g.collectUnions(u)
	}
	for _, d := range b.Defs {
		g.collectUnions(d)
	}

	if err := g.writeEnums(); err != nil {
		return nil, err
	}
	if err := g.writeStructs(); err != nil {
		return nil, err
	}
	if err := g.writeUnions(); err != nil {
		return nil, err
	}
	g.writeFactories()

	var file bytes.Buffer
	file.WriteString("// Code generated by contractgen from orbit-runtime schema/v3/contracts.json. DO NOT EDIT.\n\n")
	fmt.Fprintf(&file, "package %s\n\nimport (\n\t\"encoding/json\"\n\t\"fmt\"\n", pkg)
	if g.usesTime {
		file.WriteString("\t\"time\"\n")
	}
	file.WriteString(")\n\n")
	file.Write(g.out.Bytes())
	src, err := format.Source(file.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt generated code: %w\n%s", err, file.String())
	}
	return src, nil
}

// collectUnions finds every discriminated union by its x-go-type, wherever
// pydantic inlined it.
func (g *generator) collectUnions(node any) {
	switch x := node.(type) {
	case map[string]any:
		if name, ok := x["x-go-type"].(string); ok {
			g.unions[name] = x
		}
		for _, v := range x {
			g.collectUnions(v)
		}
	case []any:
		for _, v := range x {
			g.collectUnions(v)
		}
	}
}

func (g *generator) writeEnums() error {
	for _, name := range sortedKeys(g.b.Enums) {
		fmt.Fprintf(&g.out, "// %s is a named string set from the contract.\ntype %s string\n\nconst (\n", name, name)
		for _, value := range g.b.Enums[name] {
			fmt.Fprintf(&g.out, "\t%s%s %s = %q\n", name, goName(value), name, value)
		}
		g.out.WriteString(")\n\n")
	}
	return nil
}

func (g *generator) writeStructs() error {
	for _, name := range sortedKeys(g.b.Defs) {
		if name == "JsonValue" {
			continue
		}
		def := g.b.Defs[name]
		if def["type"] != "object" {
			return fmt.Errorf("definition %s is not an object", name)
		}
		if doc, ok := def["description"].(string); ok {
			for _, line := range strings.Split(strings.TrimSpace(doc), "\n") {
				fmt.Fprintf(&g.out, "// %s\n", strings.TrimSpace(line))
			}
		}
		fmt.Fprintf(&g.out, "type %s struct {\n", name)
		props, _ := def["properties"].(map[string]any)
		required := map[string]bool{}
		if list, ok := def["required"].([]any); ok {
			for _, r := range list {
				required[r.(string)] = true
			}
		}
		for _, prop := range sortedKeys(props) {
			field, err := g.field(prop, props[prop].(map[string]any), required[prop])
			if err != nil {
				return fmt.Errorf("%s.%s: %w", name, prop, err)
			}
			g.out.WriteString(field)
		}
		g.out.WriteString("}\n\n")
	}
	return nil
}

func (g *generator) field(prop string, s schema, required bool) (string, error) {
	nullable := false
	if any, ok := s["anyOf"].([]any); ok {
		inner, err := nonNull(any)
		if err != nil {
			return "", err
		}
		s, nullable = inner, true
	}
	goType, kind, err := g.goType(s)
	if err != nil {
		return "", err
	}
	tag := prop
	switch {
	case kind == kindConst:
		// Constant fields (tags, schema versions) are plain strings; the
		// receiver fills in the default when they are left out.
		tag += ",omitempty"
	case kind == kindCollection:
		if !required {
			tag += ",omitempty"
		}
	case !required || nullable:
		goType = "*" + goType
		if !required {
			tag += ",omitempty"
		}
	}
	return fmt.Sprintf("\t%s %s `json:%q`\n", goName(prop), goType, tag), nil
}

type typeKind int

const (
	kindValue typeKind = iota
	kindCollection
	kindConst
)

func (g *generator) goType(s schema) (string, typeKind, error) {
	if name, ok := s["x-go-type"].(string); ok {
		return name, kindValue, nil
	}
	if ref, ok := s["$ref"].(string); ok {
		name := strings.TrimPrefix(ref, "#/$defs/")
		if name == "JsonValue" {
			return "json.RawMessage", kindCollection, nil
		}
		return name, kindValue, nil
	}
	if _, ok := s["const"]; ok {
		return "string", kindConst, nil
	}
	if values, ok := s["enum"].([]any); ok {
		strs := make([]string, 0, len(values))
		for _, v := range values {
			strs = append(strs, fmt.Sprint(v))
		}
		if name, ok := g.enumByKey[enumKey(strs)]; ok {
			return name, kindValue, nil
		}
		return "string", kindValue, nil
	}
	if len(s) == 0 {
		return "json.RawMessage", kindCollection, nil
	}
	switch s["type"] {
	case "string":
		if s["format"] == "date-time" {
			g.usesTime = true
			return "time.Time", kindValue, nil
		}
		return "string", kindValue, nil
	case "integer":
		return "int64", kindValue, nil
	case "number":
		return "float64", kindValue, nil
	case "boolean":
		return "bool", kindValue, nil
	case "array":
		items, _ := s["items"].(map[string]any)
		inner, _, err := g.goType(items)
		if err != nil {
			return "", 0, err
		}
		return "[]" + inner, kindCollection, nil
	case "object":
		values, ok := s["additionalProperties"].(map[string]any)
		if !ok {
			return "", 0, fmt.Errorf("inline object without additionalProperties schema")
		}
		inner, _, err := g.goType(values)
		if err != nil {
			return "", 0, err
		}
		return "map[string]" + inner, kindCollection, nil
	}
	return "", 0, fmt.Errorf("unsupported schema %v", s)
}

func nonNull(options []any) (schema, error) {
	var kept []schema
	for _, o := range options {
		m := o.(map[string]any)
		if m["type"] == "null" {
			continue
		}
		kept = append(kept, m)
	}
	if len(kept) != 1 || len(options) != 2 {
		return nil, fmt.Errorf("anyOf must be exactly one type plus null")
	}
	return kept[0], nil
}

func (g *generator) writeUnions() error {
	for _, name := range sortedKeys(g.unions) {
		u := g.unions[name]
		disc, _ := u["discriminator"].(map[string]any)
		if disc == nil {
			return fmt.Errorf("union %s has no discriminator", name)
		}
		prop, _ := disc["propertyName"].(string)
		mapping, _ := disc["mapping"].(map[string]any)
		tags := sortedKeys(mapping)
		members := map[string]string{}
		for _, tag := range tags {
			members[tag] = strings.TrimPrefix(mapping[tag].(string), "#/$defs/")
		}

		fmt.Fprintf(&g.out, "// %s is exactly one of its members, chosen by %q.\ntype %s struct {\n", name, prop, name)
		for _, tag := range tags {
			fmt.Fprintf(&g.out, "\t%s *%s\n", members[tag], members[tag])
		}
		g.out.WriteString("}\n\n")

		fmt.Fprintf(&g.out, "const (\n")
		for _, tag := range tags {
			fmt.Fprintf(&g.out, "\t%sTag%s = %q\n", name, goName(tag), tag)
		}
		g.out.WriteString(")\n\n")

		field := goName(prop)
		fmt.Fprintf(&g.out, "// Tag returns the %q value of the member that is set.\nfunc (u %s) Tag() string {\n\tswitch {\n", prop, name)
		for _, tag := range tags {
			fmt.Fprintf(&g.out, "\tcase u.%s != nil:\n\t\treturn %q\n", members[tag], tag)
		}
		g.out.WriteString("\t}\n\treturn \"\"\n}\n\n")

		fmt.Fprintf(&g.out, "func (u %s) MarshalJSON() ([]byte, error) {\n\tswitch {\n", name)
		for _, tag := range tags {
			m := members[tag]
			fmt.Fprintf(&g.out, "\tcase u.%s != nil:\n\t\tv := *u.%s\n\t\tv.%s = %q\n\t\treturn json.Marshal(v)\n", m, m, field, tag)
		}
		fmt.Fprintf(&g.out, "\t}\n\treturn nil, fmt.Errorf(\"contract: %s has no member set\")\n}\n\n", name)

		fmt.Fprintf(&g.out, "func (u *%s) UnmarshalJSON(data []byte) error {\n", name)
		fmt.Fprintf(&g.out, "\tvar head struct {\n\t\tTag string `json:%q`\n\t}\n", prop)
		fmt.Fprintf(&g.out, "\tif err := json.Unmarshal(data, &head); err != nil {\n\t\treturn fmt.Errorf(\"contract: decode %s: %%w\", err)\n\t}\n\tswitch head.Tag {\n", name)
		for _, tag := range tags {
			m := members[tag]
			fmt.Fprintf(&g.out, "\tcase %q:\n\t\tvar v %s\n\t\tif err := json.Unmarshal(data, &v); err != nil {\n\t\t\treturn fmt.Errorf(\"contract: decode %s %s: %%w\", err)\n\t\t}\n\t\t*u = %s{%s: &v}\n", tag, m, name, tag, name, m)
		}
		fmt.Fprintf(&g.out, "\tdefault:\n\t\treturn fmt.Errorf(\"contract: unknown %s %s %%q\", head.Tag)\n\t}\n\treturn nil\n}\n\n", name, prop)

		if err := g.writeRetention(name, tags, members); err != nil {
			return err
		}
	}
	return nil
}

// writeRetention emits <Union>Retention when every member fixes a
// "retention" constant, which is how the event union marks durable and
// ephemeral types (09 §2).
func (g *generator) writeRetention(name string, tags []string, members map[string]string) error {
	values := map[string]string{}
	for _, tag := range tags {
		props, _ := g.b.Defs[members[tag]]["properties"].(map[string]any)
		retention, _ := props["retention"].(map[string]any)
		value, ok := retention["const"].(string)
		if !ok {
			return nil
		}
		values[tag] = value
	}
	fmt.Fprintf(&g.out, "// %sRetention maps each %s tag to durable or ephemeral.\nvar %sRetention = map[string]string{\n", name, name, name)
	for _, tag := range tags {
		fmt.Fprintf(&g.out, "\t%q: %q,\n", tag, values[tag])
	}
	g.out.WriteString("}\n\n")
	return nil
}

// writeFactories lists the top-level models and unions by name so tests
// can decode the exported examples without reflection.
func (g *generator) writeFactories() {
	names := append([]string{}, g.b.Models...)
	names = append(names, sortedKeys(g.b.Unions)...)
	sort.Strings(names)
	g.out.WriteString("var contractFactories = map[string]func() any{\n")
	for _, n := range names {
		fmt.Fprintf(&g.out, "\t%q: func() any { return new(%s) },\n", n, n)
	}
	g.out.WriteString("}\n")
}

var initialisms = map[string]string{
	"id": "ID", "ids": "IDs", "url": "URL", "uri": "URI", "json": "JSON",
	"usd": "USD", "api": "API", "http": "HTTP", "sop": "SOP",
}

func goName(s string) string {
	parts := strings.FieldsFunc(strings.ToLower(s), func(r rune) bool {
		return r == '_' || r == '.' || r == '-' || r == ':' || r == '/'
	})
	var b strings.Builder
	for _, p := range parts {
		if up, ok := initialisms[p]; ok {
			b.WriteString(up)
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

func enumKey(values []string) string {
	sorted := append([]string{}, values...)
	sort.Strings(sorted)
	return strings.Join(sorted, "\x00")
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
